---
title: "Assignment 1: Linear Models"
author: "YOUR NAME HERE"
output: html_document
---

```{r, include = FALSE}
## This part allows your file to knit even if there are errors.

knitr::opts_chunk$set(error = TRUE)

```


```{r}
library(tidyverse)
library(tidymodels)
```


## Part One

#### Q1

```{r}
ins <- read_csv("https://www.dropbox.com/s/bocjjyo1ehr5auz/insurance_costs_1.csv?dl=1")
```

    
#### Q2

```{r}
ins <- ins %>%
  mutate(
    #### your code here
  )
```


#### Q3

```{r, eval = FALSE}
### Code for scatter plot
ins %>%
  ggplot(aes(x = ???, y = ???, color = ???)) +
  geom_point()

### Code for boxplot
ins %>%
  ggplot(aes(x = ???, y = ???, fill = ???)) +
  geom_boxplot()
```


## Part Two

#### Q1


#### Q2


#### Q3


#### Q4


## Part Three

#### Q1


#### Q2

```{r, eval = FALSE}
charges ~ poly(age, 2)
```


#### Q3


#### Q4


#### Q5


#### Q6


```{r, eval = FALSE}
<YOUR DATASET> %>%
  ggplot() +
  geom_point(aes(x = age, y = charges)) +
  geom_line(aes(x = age, y = predicted_charges))

```

## Part Four


