system("python3 -m pip install jupyter")
system("python3 -m pip install seaborn")
system("python3 -m pip install pandas")
system("python3 -m pip install numpy")
system("python3 -m pip install sklearn")